In [1]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from seaborn) (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [2]:
pip install seaborn pandas matplotlib numpy scipy

Requirement already satisfied: seaborn in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (0.13.2)
Requirement already satisfied: pandas in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (2.2.3)
Requirement already satisfied: matplotlib in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (3.10.1)
Requirement already satisfied: numpy in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (1.26.4)
Requirement already satisfied: scipy in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (1.15.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: six>=1.5 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
!pip install missingno

Requirement already satisfied: missingno in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (0.5.2)
Requirement already satisfied: numpy in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from missingno) (1.26.4)
Requirement already satisfied: matplotlib in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from missingno) (3.10.1)
Requirement already satisfied: scipy in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from missingno) (1.15.2)
Requirement already satisfied: seaborn in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from missingno) (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->missingno) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->missingno) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->missingno) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->missingno) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->missingno) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->missingno) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->missingno) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->missingno) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from seaborn->missingno) (2.2.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from pandas>=1.2->seaborn->missingno) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from pandas>=1.2->seaborn->missingno) (2025.1)
Requirement already satisfied: six>=1.5 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from python-dateutil>=2.7->matplotlib->missingno) (1.17.0)

In [4]:
!pip install plotly

Requirement already satisfied: plotly in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (6.0.1)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from plotly) (1.29.0)
Requirement already satisfied: packaging in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from plotly) (24.2)

In [5]:
!pip install wordcloud

Requirement already satisfied: wordcloud in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (1.9.4)
Requirement already satisfied: numpy>=1.6.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from wordcloud) (1.26.4)
Requirement already satisfied: pillow in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from wordcloud) (11.1.0)
Requirement already satisfied: matplotlib in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from wordcloud) (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->wordcloud) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->wordcloud) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->wordcloud) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->wordcloud) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->wordcloud) (24.2)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->wordcloud) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->wordcloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from python-dateutil>=2.7->matplotlib->wordcloud) (1.17.0)

In [6]:

import pandas as pd
import numpy as np

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
import missingno as msno
import plotly.express as px
import plotly.figure_factory as ff
import plotly.graph_objects as go
from wordcloud import WordCloud

%matplotlib inline
sns.set_style('darkgrid')
mpl.rcParams['font.size'] = 14
mpl.rcParams['figure.facecolor'] = '#00000000'
mpl.rcParams['font.size'] = 14
mpl.rcParams['figure.facecolor'] = '#00000000'

import os
from wordcloud import WordCloud

import warnings
warnings.filterwarnings("ignore")

df = pd.read_csv("Case1.csv")

df.head()

,loan_id,source,financial_institution,interest_rate,unpaid_principal_bal,Loan_term,origination_date,first_payment_date,loan_to_value,number_of_borrowers,...,Occupation,Borrower_State,EducationLevel,MaritalStatus,Age,Gender,EmploymentStatus,NumberOfDependents,Annual Income,m1
0,8.110000e+11,Y,Browning-Hart,3.750,192000,18,01-02-2012,Apr-12,80,2,...,Assistant Engineer,PA,Bachelor's,Married,51,Female,Employed,2,6620.689655,0
1,7.220000e+11,X,OTHER,4.250,308000,6,01-02-2012,Apr-12,95,1,...,Team Member,CO,PhD,Married,43,Male,Employed,1,9058.823529,0
2,7.800000e+11,Y,Edwards-Hoffman,4.500,80000,12,01-01-2012,Mar-12,73,1,...,OPERATIONS MGR,MS,High School,Married,18,Male,Employed,2,1951.219512,0
3,6.690000e+11,X,OTHER,3.125,60000,36,01-02-2012,Apr-12,33,1,...,Quality Assurance,TX,PhD,Divorced,34,Female,Employed,1,3333.333333,0
4,3.940000e+11,X,OTHER,3.375,195000,36,01-01-2012,Mar-12,75,1,...,Mechanic,MN,High School,Single,65,Female,Employed,1,7800.000000,1

In [7]:
import numpy as np 
def get_column_min_max(df, column_name):
    if column_name not in df.columns:
        return f"Column '{column_name}' does not exist in the DataFrame."
    
    if not np.issubdtype(df[column_name].dtype, np.number):
        return f"Column '{column_name}' is not numeric."

    max_val = df[column_name].max()
    min_val = df[column_name].min()
    return max_val, min_val


column_name = "Annual Income" 
max_val, min_val = get_column_min_max(df, column_name)
print(f"Max of {column_name}:", max_val)
print(f"Min of {column_name}:", min_val)

Max of Annual Income: 470000.0
Min of Annual Income: 341.4634146

In [8]:
import numpy as np  

def get_column_min_max(df, column_name):
    if column_name not in df.columns:
        return f"Column '{column_name}' does not exist in the DataFrame."
    
    if not np.issubdtype(df[column_name].dtype, np.number):
        return f"Column '{column_name}' is not numeric."

    max_val = df[column_name].max()
    min_val = df[column_name].min()
    return max_val, min_val

column_name = "interest_rate"  
result = get_column_min_max(df, column_name)

if isinstance(result, tuple):
    max_val, min_val = result
    print(f"Max of {column_name}:", max_val)
    print(f"Min of {column_name}:", min_val)
else:
    print(result)

Max of interest_rate: 6.75
Min of interest_rate: 2.25

In [9]:
import numpy as np  
def get_column_min_max(df, column_name):
    if column_name not in df.columns:
        return f"Column '{column_name}' does not exist in the DataFrame."
    
    if not np.issubdtype(df[column_name].dtype, np.number):
        return f"Column '{column_name}' is not numeric."

    max_val = df[column_name].max()
    min_val = df[column_name].min()
    return max_val, min_val


column_name = "unpaid_principal_bal"  
result = get_column_min_max(df, column_name)

if isinstance(result, tuple):
    max_val, min_val = result
    print(f"Max of {column_name}:", max_val)
    print(f"Min of {column_name}:", min_val)
else:
    print(result)

Max of unpaid_principal_bal: 1200000
Min of unpaid_principal_bal: 11000

In [10]:
import numpy as np  
def get_column_min_max(df, column_name):
    if column_name not in df.columns:
        return f"Column '{column_name}' does not exist in the DataFrame."
    
    if not np.issubdtype(df[column_name].dtype, np.number):
        return f"Column '{column_name}' is not numeric."

    max_val = df[column_name].max()
    min_val = df[column_name].min()
    return max_val, min_val


column_name = "loan_to_value"  
result = get_column_min_max(df, column_name)

if isinstance(result, tuple):
    max_val, min_val = result
    print(f"Max of {column_name}:", max_val)
    print(f"Min of {column_name}:", min_val)
else:
    print(result)

Max of loan_to_value: 97
Min of loan_to_value: 6

In [11]:

import numpy as np  
def get_column_min_max(df, column_name):
    if column_name not in df.columns:
        return f"Column '{column_name}' does not exist in the DataFrame."
    
    if not np.issubdtype(df[column_name].dtype, np.number):
        return f"Column '{column_name}' is not numeric."

    max_val = df[column_name].max()
    min_val = df[column_name].min()
    return max_val, min_val


column_name = "debt_to_income_ratio"  
result = get_column_min_max(df, column_name)

if isinstance(result, tuple):
    max_val, min_val = result
    print(f"Max of {column_name}:", max_val)
    print(f"Min of {column_name}:", min_val)
else:
    print(result)

Max of debt_to_income_ratio: 64
Min of debt_to_income_ratio: 1

In [12]:



import numpy as np  
def get_column_min_max(df, column_name):
    if column_name not in df.columns:
        return f"Column '{column_name}' does not exist in the DataFrame."
    
    if not np.issubdtype(df[column_name].dtype, np.number):
        return f"Column '{column_name}' is not numeric."

    max_val = df[column_name].max()
    min_val = df[column_name].min()
    return max_val, min_val


column_name = "borrower_credit_score"  
result = get_column_min_max(df, column_name)

if isinstance(result, tuple):
    max_val, min_val = result
    print(f"Max of {column_name}:", max_val)
    print(f"Min of {column_name}:", min_val)
else:
    print(result)

Max of borrower_credit_score: 840
Min of borrower_credit_score: 480

In [13]:
df['borrower_credit_score'] = df['borrower_credit_score'].replace(0, 730)

In [14]:
import numpy as np  
def get_column_min_max(df, column_name):
    if column_name not in df.columns:
        return f"Column '{column_name}' does not exist in the DataFrame."
    
    if not np.issubdtype(df[column_name].dtype, np.number):
        return f"Column '{column_name}' is not numeric."

    max_val = df[column_name].max()
    min_val = df[column_name].min()
    return max_val, min_val


column_name = "borrower_credit_score"  
result = get_column_min_max(df, column_name)

if isinstance(result, tuple):
    max_val, min_val = result
    print(f"Max of {column_name}:", max_val)
    print(f"Min of {column_name}:", min_val)
else:
    print(result)

Max of borrower_credit_score: 840
Min of borrower_credit_score: 480

In [15]:

import numpy as np  
def get_column_min_max(df, column_name):
    if column_name not in df.columns:
        return f"Column '{column_name}' does not exist in the DataFrame."
    
    if not np.issubdtype(df[column_name].dtype, np.number):
        return f"Column '{column_name}' is not numeric."

    max_val = df[column_name].max()
    min_val = df[column_name].min()
    return max_val, min_val



column_name = "insurance_percent"  
result = get_column_min_max(df, column_name)

if isinstance(result, tuple):
    max_val, min_val = result
    print(f"Max of {column_name}:", max_val)
    print(f"Min of {column_name}:", min_val)
else:
    print(result)

Max of insurance_percent: 40
Min of insurance_percent: 0

In [16]:

import numpy as np  
def get_column_min_max(df, column_name):
    if column_name not in df.columns:
        return f"Column '{column_name}' does not exist in the DataFrame."
    
    if not np.issubdtype(df[column_name].dtype, np.number):
        return f"Column '{column_name}' is not numeric."

    max_val = df[column_name].max()
    min_val = df[column_name].min()
    return max_val, min_val



column_name = "Age"  
result = get_column_min_max(df, column_name)

if isinstance(result, tuple):
    max_val, min_val = result
    print(f"Max of {column_name}:", max_val)
    print(f"Min of {column_name}:", min_val)
else:
    print(result)

Max of Age: 80
Min of Age: 18

In [17]:


import numpy as np  
def get_column_min_max(df, column_name):
    if column_name not in df.columns:
        return f"Column '{column_name}' does not exist in the DataFrame."
    
    if not np.issubdtype(df[column_name].dtype, np.number):
        return f"Column '{column_name}' is not numeric."

    max_val = df[column_name].max()
    min_val = df[column_name].min()
    return max_val, min_val


column_name = "NumberOfDependents"  
result = get_column_min_max(df, column_name)

if isinstance(result, tuple):
    max_val, min_val = result
    print(f"Max of {column_name}:", max_val)
    print(f"Min of {column_name}:", min_val)
else:
    print(result)

Max of NumberOfDependents: 5
Min of NumberOfDependents: 0

In [18]:
df_copy = df.copy()

In [19]:
import numpy as np

if {'unpaid_principal_bal', 'debt_to_income_ratio', 'Annual Income'}.issubset(df_copy.columns):
    safe_dti = df_copy['debt_to_income_ratio'].replace(0, np.nan)
    df_copy['Annual Income'] = df_copy['unpaid_principal_bal'] / safe_dti
    df_copy['Annual income'] = df_copy['Annual Income'].replace([np.inf, -np.inf], np.nan).fillna(0)
else:
    print("Error")

In [20]:
df_copy['Annual Income'].head()

0    6620.689655
1    9058.823529
2    1951.219512
3    3333.333333
4    7800.000000
Name: Annual Income, dtype: float64

In [21]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)
print(df.head())

        loan_id source financial_institution  interest_rate  unpaid_principal_bal  Loan_term origination_date first_payment_date  loan_to_value  number_of_borrowers  debt_to_income_ratio  borrower_credit_score loan_purpose  insurance_percent  co-borrower_credit_score  insurance_type         Occupation  Borrower_State EducationLevel MaritalStatus  Age  Gender EmploymentStatus  NumberOfDependents  Annual Income  m1
0  8.110000e+11      Y         Browning-Hart          3.750                192000         18       01-02-2012             Apr-12             80                    2                    29                    809          C86                  0                       812               0  Assistant Engineer             PA     Bachelor's       Married   51  Female         Employed                   2    6620.689655   0
1  7.220000e+11      X                 OTHER          4.250                308000          6       01-02-2012             Apr-12             95                    1                    34                    712          A23                 30                         0               0         Team Member             CO            PhD       Married   43    Male         Employed                   1    9058.823529   0
2  7.800000e+11      Y       Edwards-Hoffman          4.500                 80000         12       01-01-2012             Mar-12             73                    1                    41                    690          C86                  0                         0               0      OPERATIONS MGR             MS    High School       Married   18    Male         Employed                   2    1951.219512   0
3  6.690000e+11      X                 OTHER          3.125                 60000         36       01-02-2012             Apr-12             33                    1                    18                    814          C86                  0                         0               0   Quality Assurance             TX            PhD      Divorced   34  Female         Employed                   1    3333.333333   0
4  3.940000e+11      X                 OTHER          3.375                195000         36       01-01-2012             Mar-12             75                    1                    25                    797          B12                  0                         0               0            Mechanic             MN    High School        Single   65  Female         Employed                   1    7800.000000   1

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116058 entries, 0 to 116057
Data columns (total 26 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   loan_id                   116058 non-null  float64
 1   source                    116058 non-null  object
 2   financial_institution     116058 non-null  object
 3   interest_rate             116058 non-null  float64
 4   unpaid_principal_bal      116058 non-null  int64
 5   Loan_term                 116058 non-null  int64
 6   origination_date          116058 non-null  object
 7   first_payment_date        116058 non-null  object
 8   loan_to_value             116058 non-null  int64
 9   number_of_borrowers       116058 non-null  int64
 10  debt_to_income_ratio      116058 non-null  int64
 11  borrower_credit_score     116058 non-null  int64
 12  loan_purpose              116058 non-null  object
 13  insurance_percent         116058 non-null  int64
 14  co-borrower_credit_score  116058 non-null  int64
 15  insurance_type            116058 non-null  int64
 16  Occupation                116058 non-null  object
 17  Borrower_State            116058 non-null  object
 18  EducationLevel            116058 non-null  object
 19  MaritalStatus             116058 non-null  object
 20  Age                       116058 non-null  int64
 21  Gender                    116058 non-null  object
 22  EmploymentStatus          116058 non-null  object
 23  NumberOfDependents        116058 non-null  int64
 24  Annual Income             116058 non-null  float64
 25  m1                        116058 non-null  int64
dtypes: float64(3), int64(12), object(11)
memory usage: 23.0+ MB

In [23]:
print(df.shape)

(116058, 26)

In [24]:
df.describe()

            loan_id  interest_rate  unpaid_principal_bal      Loan_term  loan_to_value  number_of_borrowers  debt_to_income_ratio  borrower_credit_score  insurance_percent  co-borrower_credit_score  insurance_type            Age  NumberOfDependents  Annual Income             m1
count  1.160580e+05  116058.000000          1.160580e+05  116058.000000  116058.000000        116058.000000         116058.000000          116058.000000      116058.000000             116058.000000   116058.000000  116058.000000       116058.000000  116058.000000  116058.000000
mean   5.494154e+11       3.868961          2.082262e+05      20.999225      67.431939             1.593186             30.742293             770.247566           2.786288                459.611565        0.003257      39.701287            1.528253    7674.774034       0.299997
std    2.597569e+11       0.461020          1.146851e+05      10.246692      17.291719             0.491242              9.730798              39.010862           8.096464                381.946926        0.056977      11.619786            1.389666    6373.272601       0.458258
min    1.000000e+11       2.250000          1.100000e+04       6.000000       6.000000             1.000000              1.000000             480.000000           0.000000                  0.000000        0.000000      18.000000            0.000000     341.463415       0.000000
25%    3.240000e+11       3.500000          1.200000e+05      12.000000      57.000000             1.000000             23.000000             751.000000           0.000000                  0.000000        0.000000      31.000000            0.000000    3920.000000       0.000000
50%    5.490000e+11       3.875000          1.830000e+05      18.000000      72.000000             2.000000             31.000000             782.000000           0.000000                740.000000        0.000000      40.000000            1.000000    6256.410256       0.000000
75%    7.740000e+11       4.125000          2.780000e+05      30.000000      80.000000             2.000000             39.000000             800.000000           0.000000                791.000000        0.000000      48.000000            3.000000    9692.307692       1.000000
max    1.000000e+12       6.750000          1.200000e+06      36.000000      97.000000             2.000000             64.000000             840.000000          40.000000                836.000000        1.000000      80.000000            5.000000  470000.000000       1.000000

In [25]:
print(df.isnull().sum())

loan_id                     0
source                      0
financial_institution       0
interest_rate               0
unpaid_principal_bal        0
Loan_term                   0
origination_date            0
first_payment_date          0
loan_to_value               0
number_of_borrowers         0
debt_to_income_ratio        0
borrower_credit_score       0
loan_purpose                0
insurance_percent           0
co-borrower_credit_score    0
insurance_type              0
Occupation                  0
Borrower_State              0
EducationLevel              0
MaritalStatus               0
Age                         0
Gender                      0
EmploymentStatus            0
NumberOfDependents          0
Annual Income               0
m1                          0
dtype: int64

In [26]:
import pandas as pd

duplicate_rows = df[df.duplicated()]
print(duplicate_rows)

Empty DataFrame
Columns: [loan_id, source, financial_institution, interest_rate, unpaid_principal_bal, Loan_term, origination_date, first_payment_date, loan_to_value, number_of_borrowers, debt_to_income_ratio, borrower_credit_score, loan_purpose, insurance_percent, co-borrower_credit_score, insurance_type, Occupation , Borrower_State, EducationLevel, MaritalStatus, Age, Gender, EmploymentStatus, NumberOfDependents, Annual Income, m1]
Index: []

In [27]:
unique_genders = df['Gender'].unique()
print(unique_genders)

['Female' 'Male' 'Other']

In [28]:
unique_genders = df['source'].unique()
print(unique_genders)

['Y' 'X' 'Z']

In [29]:
unique_genders = df['insurance_type'].unique()
print(unique_genders)

[0 1]

In [30]:
unique_genders = df['loan_purpose'].unique()
print(unique_genders)

['C86' 'A23' 'B12']

In [31]:
unique_genders = df['Occupation '].unique()
print(unique_genders)

['Assistant Engineer' 'Team Member' 'OPERATIONS MGR' ...
 'Communication Operator' 'Nurse Aid' 'Merchandising supervisor']

In [32]:
unique_genders = df['first_payment_date'].unique()
print(unique_genders)

['Apr-12' 'Mar-12' 'May-12' 'Feb-12']

In [33]:
unique_genders = df['Age'].unique()
print(unique_genders)

[51 43 18 34 65 33 22 26 52 49 19 27 20 39 35 36 28 45 42 58 38 37 41 31
 60 47 32 24 30 44 46 54 21 59 53 40 57 25 23 56 29 48 50 63 69 55 62 61
 66 73 64 72 71 68 67 78 80 70 75 77 79 76 74]

In [34]:

unique_genders = df['EducationLevel'].unique()
print(unique_genders)

["Bachelor's" 'PhD' 'High School' "Master's" 'Doctorate']

In [35]:

unique_genders = df['Annual Income'].unique()
print(unique_genders)

[ 6620.689655  9058.823529  1951.219512 ... 31615.38462  22923.07692
 10970.58824 ]

In [36]:
unique_genders = df['financial_institution'].unique()
print(unique_genders)

['Browning-Hart' 'OTHER' 'Edwards-Hoffman' 'Swanson, Newton and Miller'
 'Anderson-Taylor' 'Sanchez, Hays and Wilkerson' 'Chapman-Mcmahon'
 'Nicholson Group' 'Romero, Woods and Johnson' 'Martinez, Duffy and Bird'
 'Miller, Mcclure and Allen' 'Cole, Brooks and Vincent'
 'Turner, Baldwin and Rhodes' 'Richards-Walters' 'Sanchez-Robinson'
 'Suarez Inc' 'Taylor, Hunt and Rodriguez' 'Richardson Ltd'
 'Thornton-Davis']

In [37]:
df_copy.reset_index(inplace = True)

In [38]:
df.head()

        loan_id source financial_institution  interest_rate  unpaid_principal_bal  Loan_term origination_date first_payment_date  loan_to_value  number_of_borrowers  debt_to_income_ratio  borrower_credit_score loan_purpose  insurance_percent  co-borrower_credit_score  insurance_type         Occupation  Borrower_State EducationLevel MaritalStatus  Age  Gender EmploymentStatus  NumberOfDependents  Annual Income  m1
0  8.110000e+11      Y         Browning-Hart          3.750                192000         18       01-02-2012             Apr-12             80                    2                    29                    809          C86                  0                       812               0  Assistant Engineer             PA     Bachelor's       Married   51  Female         Employed                   2    6620.689655   0
1  7.220000e+11      X                 OTHER          4.250                308000          6       01-02-2012             Apr-12             95                    1                    34                    712          A23                 30                         0               0         Team Member             CO            PhD       Married   43    Male         Employed                   1    9058.823529   0
2  7.800000e+11      Y       Edwards-Hoffman          4.500                 80000         12       01-01-2012             Mar-12             73                    1                    41                    690          C86                  0                         0               0      OPERATIONS MGR             MS    High School       Married   18    Male         Employed                   2    1951.219512   0
3  6.690000e+11      X                 OTHER          3.125                 60000         36       01-02-2012             Apr-12             33                    1                    18                    814          C86                  0                         0               0   Quality Assurance             TX            PhD      Divorced   34  Female         Employed                   1    3333.333333   0
4  3.940000e+11      X                 OTHER          3.375                195000         36       01-01-2012             Mar-12             75                    1                    25                    797          B12                  0                         0               0            Mechanic             MN    High School        Single   65  Female         Employed                   1    7800.000000   1

Feature Engineering

In [39]:
df_copy = df_copy.drop(df_copy[df_copy['Age'] >= 80].index, axis=0)

In [40]:
df_copy['age_group'] = pd.cut(df_copy['Age'],
                           bins=[18, 25, 35, 45, 55, 65, 80],
                           labels=['18-24', '25-34', '35-44', '45-54', '55-64', '65-79'])

In [41]:
max_ = df_copy['Age'].max()
min_ = df_copy['Age'].min()
print(f"maximum Age {max_}")
print(f"minimum Age {min_}")

def age_group(arr):
    lenarr = len(arr)
    for i in range(0,lenarr-1):
        next = arr[i]+1
        num_people = df_copy['Age'].between(next,arr[i+1]).sum()
        print(f'Age between {next} and {arr[i+1]}: Number of people {num_people}')
        
age_group([0 ,18, 26, 36, 46, 56, 66,76,79,85])

maximum Age 79
minimum Age 18
Age between 1 and 18: Number of people 4665
Age between 19 and 26: Number of people 11490
Age between 27 and 36: Number of people 30299
Age between 37 and 46: Number of people 37108
Age between 47 and 56: Number of people 23390
Age between 57 and 66: Number of people 7699
Age between 67 and 76: Number of people 1293
Age between 77 and 79: Number of people 65
Age between 80 and 85: Number of people 0

In [42]:
df_copy['age_group'].dtype

CategoricalDtype(categories=['18-24', '25-34', '35-44', '45-54', '55-64', '65-79'], ordered=True, categories_dtype=object)

In [43]:
print(df_copy.columns.tolist())

['index', 'loan_id', 'source', 'financial_institution', 'interest_rate', 'unpaid_principal_bal', 'Loan_term', 'origination_date', 'first_payment_date', 'loan_to_value', 'number_of_borrowers', 'debt_to_income_ratio', 'borrower_credit_score', 'loan_purpose', 'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'Occupation ', 'Borrower_State', 'EducationLevel', 'MaritalStatus', 'Age', 'Gender', 'EmploymentStatus', 'NumberOfDependents', 'Annual Income', 'm1', 'Annual income', 'age_group']

In [44]:
data = df_copy.copy()

In [45]:
print(data.columns.tolist())

['index', 'loan_id', 'source', 'financial_institution', 'interest_rate', 'unpaid_principal_bal', 'Loan_term', 'origination_date', 'first_payment_date', 'loan_to_value', 'number_of_borrowers', 'debt_to_income_ratio', 'borrower_credit_score', 'loan_purpose', 'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'Occupation ', 'Borrower_State', 'EducationLevel', 'MaritalStatus', 'Age', 'Gender', 'EmploymentStatus', 'NumberOfDependents', 'Annual Income', 'm1', 'Annual income', 'age_group']

In [46]:
import pandas as pd

bins = [0, 25000, 50000, 75000, 100000, float('inf')]
labels = ['low', 'low-middle', 'middle', 'high-middle', 'high']

data['income_group'] = pd.cut(data['Annual Income'], bins=bins, labels=labels)
print(data)

         index       loan_id source       financial_institution  interest_rate  unpaid_principal_bal  Loan_term origination_date first_payment_date  loan_to_value  number_of_borrowers  debt_to_income_ratio  borrower_credit_score loan_purpose  insurance_percent  co-borrower_credit_score  insurance_type          Occupation  Borrower_State EducationLevel MaritalStatus  Age  Gender EmploymentStatus  NumberOfDependents  Annual Income  m1  Annual income age_group income_group
0            0  8.110000e+11      Y               Browning-Hart          3.750                192000         18       01-02-2012             Apr-12             80                    2                    29                    809          C86                  0                       812               0   Assistant Engineer             PA     Bachelor's       Married   51  Female         Employed                   2    6620.689655   0    6620.689655     45-54          low
1            1  7.220000e+11      X                       OTHER          4.250                308000          6       01-02-2012             Apr-12             95                    1                    34                    712          A23                 30                         0               0          Team Member             CO            PhD       Married   43    Male         Employed                   1    9058.823529   0    9058.823529     35-44          low
2            2  7.800000e+11      Y             Edwards-Hoffman          4.500                 80000         12       01-01-2012             Mar-12             73                    1                    41                    690          C86                  0                         0               0       OPERATIONS MGR             MS    High School       Married   18    Male         Employed                   2    1951.219512   0    1951.219512       NaN          low
3            3  6.690000e+11      X                       OTHER          3.125                 60000         36       01-02-2012             Apr-12             33                    1                    18                    814          C86                  0                         0               0    Quality Assurance             TX            PhD      Divorced   34  Female         Employed                   1    3333.333333   0    3333.333333     25-34          low
4            4  3.940000e+11      X                       OTHER          3.375                195000         36       01-01-2012             Mar-12             75                    1                    25                    797          B12                  0                         0               0             Mechanic             MN    High School        Single   65  Female         Employed                   1    7800.000000   1    7800.000000     55-64          low
...        ...           ...    ...                         ...            ...                   ...        ...              ...                ...            ...                  ...                   ...                    ...          ...                ...                       ...             ...                  ...            ...            ...           ...  ...     ...              ...                 ...            ...  ..            ...       ...          ...
116053  116053  6.730000e+11      Y    Cole, Brooks and Vincent          3.750                147000          6       01-01-2012             Mar-12             70                    2                    44                    814          C86                  0                       807               0    General Engineer              TN    High School        Single   51  Female         Employed                   0    3340.909091   0    3340.909091     45-54          low
116054  116054  1.060000e+11      X                       OTHER          3.875                 64000         24       01-01-2012             Mar-12             46                    1                    16                    805          B12                  0                         0               0           Accountant             NY    High School      Divorced   37    Male         Employed                   1    4000.000000   0    4000.000000     35-44          low
116055  116055  7.540000e+11      X                       OTHER          3.125                300000         30       01-02-2012             Apr-12             52                    2                     9                    785          A23                  0                       794               0  electrical mechanic             CA            PhD       Married   29  Female         Employed                   0   33333.333333   1   33333.333333     25-34   low-middle
116056  116056  7.330000e+11      X                       OTHER          3.875                106000         18       01-02-2012             Apr-12             26                    2                     7                    803          A23                  0                       814               0           Management             VA    High School        Single   29    Male         Employed                   2   15142.857143   0   15142.857143     25-34          low
116057  116057  1.170000e+11      X  Swanson, Newton and Miller          5.375                 86000         18       01-01-2012             Mar-12             75                    1                    25                    714          B12                  0                         0               0     Scoring Director             MN     Bachelor's       Married   28  Female    Self-Employed                   1    3440.000000   0    3440.000000     25-34          low

[116009 rows x 30 columns]

In [47]:
data['income_group']

0                low
1                low
2                low
3                low
4                low
             ...
116053           low
116054           low
116055    low-middle
116056           low
116057           low
Name: income_group, Length: 116009, dtype: category
Categories (5, object): ['low' < 'low-middle' < 'middle' < 'high-middle' < 'high']

In [48]:
print(data.columns.tolist())

['index', 'loan_id', 'source', 'financial_institution', 'interest_rate', 'unpaid_principal_bal', 'Loan_term', 'origination_date', 'first_payment_date', 'loan_to_value', 'number_of_borrowers', 'debt_to_income_ratio', 'borrower_credit_score', 'loan_purpose', 'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'Occupation ', 'Borrower_State', 'EducationLevel', 'MaritalStatus', 'Age', 'Gender', 'EmploymentStatus', 'NumberOfDependents', 'Annual Income', 'm1', 'Annual income', 'age_group', 'income_group']

In [49]:
bins = [10000, 50000, 200000, 500000, float('inf')]
labels = ['small', 'medium', 'large', 'very large']

data['loan_amount_group'] = pd.cut(data['unpaid_principal_bal'], bins=bins, labels=labels, right=True)

In [50]:
data['loan_amount_group']

0         medium
1          large
2         medium
3         medium
4         medium
           ...
116053    medium
116054    medium
116055     large
116056    medium
116057    medium
Name: loan_amount_group, Length: 116009, dtype: category
Categories (4, object): ['small' < 'medium' < 'large' < 'very large']

In [51]:
raw_data = data.copy()

In [52]:
print(raw_data.columns.tolist())

['index', 'loan_id', 'source', 'financial_institution', 'interest_rate', 'unpaid_principal_bal', 'Loan_term', 'origination_date', 'first_payment_date', 'loan_to_value', 'number_of_borrowers', 'debt_to_income_ratio', 'borrower_credit_score', 'loan_purpose', 'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'Occupation ', 'Borrower_State', 'EducationLevel', 'MaritalStatus', 'Age', 'Gender', 'EmploymentStatus', 'NumberOfDependents', 'Annual Income', 'm1', 'Annual income', 'age_group', 'income_group', 'loan_amount_group']

In [53]:
col_list = [
    'interest_rate',
    'unpaid_principal_bal',
    'Loan_term',
    'loan_to_value',
    'number_of_borrowers',
    'debt_to_income_ratio',
    'borrower_credit_score',
    'co-borrower_credit_score',
    'insurance_percent',
    'insurance_type',
    'loan_purpose',
    'EducationLevel',
    'MaritalStatus',
    'Age',
    'Gender',
    'EmploymentStatus',
    'NumberOfDependents',
    'Annual Income',  
    'm1',             
    'age_group',
    'income_group',
    'loan_amount_group'
]

drop_colums = [
    'index',
    'loan_id',
    'source',
    'financial_institution',
    'origination_date',
    'first_payment_date',
    'Annual income'  
]

scale_cols = [
    'interest_rate',
    'unpaid_principal_bal',
    'Loan_term',
    'loan_to_value',
    'number_of_borrowers',
    'debt_to_income_ratio',
    'borrower_credit_score',
    'co-borrower_credit_score',
    'insurance_percent',
    'Age',
    'NumberOfDependents',
    'Annual Income'
   
]
le_colums = []

ohe_colums = [
    'insurance_type',
    'loan_purpose',
    'EducationLevel',
    'MaritalStatus',
    'Gender',
    'EmploymentStatus',
    'age_group',
    'income_group',
    'loan_amount_group'
]

In [54]:
data = data.drop(drop_colums, axis=1)

In [55]:
data.columns

Index(['interest_rate', 'unpaid_principal_bal', 'Loan_term', 'loan_to_value', 'number_of_borrowers', 'debt_to_income_ratio', 'borrower_credit_score', 'loan_purpose', 'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'Occupation ', 'Borrower_State', 'EducationLevel', 'MaritalStatus', 'Age', 'Gender', 'EmploymentStatus', 'NumberOfDependents', 'Annual Income', 'm1', 'age_group', 'income_group', 'loan_amount_group'], dtype='object')

In [56]:
data = data.drop(['Occupation ', 'Borrower_State'], axis=1)

Data Preprocessing

In [57]:
X = data.drop(['m1'], axis=1)
Y = data['m1']

In [58]:
data.columns

Index(['interest_rate', 'unpaid_principal_bal', 'Loan_term', 'loan_to_value', 'number_of_borrowers', 'debt_to_income_ratio', 'borrower_credit_score', 'loan_purpose', 'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'EducationLevel', 'MaritalStatus', 'Age', 'Gender', 'EmploymentStatus', 'NumberOfDependents', 'Annual Income', 'm1', 'age_group', 'income_group', 'loan_amount_group'], dtype='object')

In [59]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,Y,test_size=0.3,random_state=12)

In [60]:
print(x_train.shape,x_test.shape)

(81206, 21) (34803, 21)

In [61]:
x_train.reset_index(inplace = True)
x_test.reset_index(inplace = True)

In [62]:
x_train.columns

Index(['index', 'interest_rate', 'unpaid_principal_bal', 'Loan_term', 'loan_to_value', 'number_of_borrowers', 'debt_to_income_ratio', 'borrower_credit_score', 'loan_purpose', 'insurance_percent', 'co-borrower_credit_score', 'insurance_type', 'EducationLevel', 'MaritalStatus', 'Age', 'Gender', 'EmploymentStatus', 'NumberOfDependents', 'Annual Income', 'age_group', 'income_group', 'loan_amount_group'], dtype='object')

In [63]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder()
ohe.fit(x_train[ohe_colums])

OneHotEncoder()

In [64]:
ohe.categories_

[array([0, 1], dtype=int64),
 array(['A23', 'B12', 'C86'], dtype=object),
 array(["Bachelor's", 'Doctorate', 'High School', "Master's", 'PhD'],
       dtype=object),
 array(['Divorced', 'Married', 'Single'], dtype=object),
 array(['Female', 'Male', 'Other'], dtype=object),
 array(['Employed', 'Self-Employed', 'Unemployed'], dtype=object),
 array(['18-24', '25-34', '35-44', '45-54', '55-64', '65-79', nan],
       dtype=object),
 array(['high', 'high-middle', 'low', 'low-middle', 'middle'], dtype=object),
 array(['large', 'medium', 'small', 'very large'], dtype=object)]

In [65]:
import numpy as np

merge_ohe_col = np.concatenate((
    ohe.categories_[0],
    ohe.categories_[1],
    ohe.categories_[2],
    ohe.categories_[3],
    ohe.categories_[4],
    ohe.categories_[5],
    ohe.categories_[6],
    ohe.categories_[7],
    ohe.categories_[8]
))

In [66]:
print(x_train.shape,x_test.shape)

(81206, 22) (34803, 22)

In [67]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

ohe = OneHotEncoder(handle_unknown='ignore')
ohe.fit(x_train[ohe_colums])

ohe_data_train = pd.DataFrame(
    ohe.transform(x_train[ohe_colums]).toarray(),
    columns=ohe.get_feature_names_out(ohe_colums),
    index=x_train.index
)

ohe_data_test = pd.DataFrame(
    ohe.transform(x_test[ohe_colums]).toarray(),
    columns=ohe.get_feature_names_out(ohe_colums),
    index=x_test.index
)

In [68]:
print(x_train.shape,x_test.shape)

(81206, 22) (34803, 22)

In [69]:
X_new_train = pd.concat([ohe_data_train, x_train], axis=1)
X_new_train = X_new_train.drop(ohe_colums, axis=1)

X_new_test = pd.concat([ohe_data_test, x_test], axis=1)
X_new_test = X_new_test.drop(ohe_colums, axis=1)

In [70]:
print(x_train.shape,x_test.shape)

(81206, 22) (34803, 22)

In [71]:
X_new_train.head()
X_new_train.shape

(81206, 48)

In [72]:
X_new_test.head()

   insurance_type_0  insurance_type_1  loan_purpose_A23  loan_purpose_B12  loan_purpose_C86  EducationLevel_Bachelor's  EducationLevel_Doctorate  EducationLevel_High School  EducationLevel_Master's  EducationLevel_PhD  MaritalStatus_Divorced  MaritalStatus_Married  MaritalStatus_Single  Gender_Female  Gender_Male  Gender_Other  EmploymentStatus_Employed  EmploymentStatus_Self-Employed  EmploymentStatus_Unemployed  age_group_18-24  age_group_25-34  age_group_35-44  age_group_45-54  age_group_55-64  age_group_65-79  age_group_nan  income_group_high  income_group_high-middle  income_group_low  income_group_low-middle  income_group_middle  loan_amount_group_large  loan_amount_group_medium  loan_amount_group_small  loan_amount_group_very large   index  interest_rate  unpaid_principal_bal  Loan_term  loan_to_value  number_of_borrowers  debt_to_income_ratio  borrower_credit_score  insurance_percent  co-borrower_credit_score  Age  NumberOfDependents  Annual Income
0               1.0               0.0               1.0               0.0               0.0                        1.0                       0.0                         0.0                      0.0                 0.0                     1.0                    0.0                   0.0            0.0          1.0           0.0                        1.0                             0.0                          0.0              0.0              0.0              0.0              1.0              0.0              0.0            0.0                0.0                       0.0               1.0                      0.0                  0.0                      0.0                       1.0                      0.0                           0.0   62374          3.000                145000         18             50                    2                    25                    792                  0                       796   46                   1    5800.000000
1               1.0               0.0               1.0               0.0               0.0                        0.0                       0.0                         0.0                      0.0                 1.0                     0.0                    1.0                   0.0            0.0          0.0           1.0                        0.0                             0.0                          1.0              0.0              0.0              0.0              1.0              0.0              0.0            0.0                0.0                       0.0               1.0                      0.0                  0.0                      0.0                       1.0                      0.0                           0.0   78459          4.000                111000         36             72                    2                    16                    780                  0                       792   50                   2    6937.500000
2               1.0               0.0               1.0               0.0               0.0                        0.0                       0.0                         1.0                      0.0                 0.0                     0.0                    0.0                   1.0            0.0          1.0           0.0                        1.0                             0.0                          0.0              0.0              0.0              0.0              0.0              1.0              0.0            0.0                0.0                       0.0               1.0                      0.0                  0.0                      1.0                       0.0                      0.0                           0.0  110125          3.875                281000         36             77                    1                    24                    808                  0                         0   60                   2   11708.333333
3               1.0               0.0               1.0               0.0               0.0                        0.0                       0.0                         1.0                      0.0                 0.0                     0.0                    1.0                   0.0            1.0          0.0           0.0                        1.0                             0.0                          0.0              0.0              0.0              1.0              0.0              0.0              0.0            0.0                0.0                       0.0               1.0                      0.0                  0.0                      1.0                       0.0                      0.0                           0.0   46998          3.875                222000         36             60                    2                    30                    734                  0                       731   36                   1    7400.000000
4               1.0               0.0               1.0               0.0               0.0                        0.0                       0.0                         0.0                      0.0                 1.0                     1.0                    0.0                   0.0            1.0          0.0           0.0                        1.0                             0.0                          0.0              0.0              0.0              0.0              0.0              1.0              0.0            0.0                0.0                       0.0               1.0                      0.0                  0.0                      1.0                       0.0                      0.0                           0.0   90938          3.875                350000         18             78                    2                    35                    763                  0                       819   57                   4   10000.000000

Applying Scaling Techniques

In [73]:
# Scaling the data

from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler

scale_cols = [
    'interest_rate',
    'unpaid_principal_bal',
    'Loan_term',
    'loan_to_value',
    'number_of_borrowers',
    'debt_to_income_ratio',
    'borrower_credit_score',
    'insurance_percent',
    'co-borrower_credit_score',
    'NumberOfDependents',
    'Annual Income',
    'Age'
]

uniform_col = []     
normal_col = scale_cols  
bimodal_col = []     

scaler_uniform = MinMaxScaler()
scaler_normal = StandardScaler()
scaler_bimodal = RobustScaler()

X_new_train.loc[:, normal_col] = scaler_normal.fit_transform(X_new_train.loc[:, normal_col])
X_new_test.loc[:, normal_col] = scaler_normal.transform(X_new_test.loc[:, normal_col])

In [74]:
X_new_test.head()

   insurance_type_0  insurance_type_1  loan_purpose_A23  loan_purpose_B12  loan_purpose_C86  EducationLevel_Bachelor's  EducationLevel_Doctorate  EducationLevel_High School  EducationLevel_Master's  EducationLevel_PhD  MaritalStatus_Divorced  MaritalStatus_Married  MaritalStatus_Single  Gender_Female  Gender_Male  Gender_Other  EmploymentStatus_Employed  EmploymentStatus_Self-Employed  EmploymentStatus_Unemployed  age_group_18-24  age_group_25-34  age_group_35-44  age_group_45-54  age_group_55-64  age_group_65-79  age_group_nan  income_group_high  income_group_high-middle  income_group_low  income_group_low-middle  income_group_middle  loan_amount_group_large  loan_amount_group_medium  loan_amount_group_small  loan_amount_group_very large   index  interest_rate  unpaid_principal_bal  Loan_term  loan_to_value  number_of_borrowers  debt_to_income_ratio  borrower_credit_score  insurance_percent  co-borrower_credit_score       Age  NumberOfDependents  Annual Income
0               1.0               0.0               1.0               0.0               0.0                        1.0                       0.0                         0.0                      0.0                 0.0                     1.0                    0.0                   0.0            0.0          1.0           0.0                        1.0                             0.0                          0.0              0.0              0.0              0.0              1.0              0.0              0.0            0.0                0.0                       0.0               1.0                      0.0                  0.0                      0.0                       1.0                      0.0                           0.0   62374      -1.886346             -0.549933  -0.293564      -1.009661             0.827024             -0.588004               0.557265          -0.345443                  0.879553  0.549038           -0.375352      -0.290895
1               1.0               0.0               1.0               0.0               0.0                        0.0                       0.0                         0.0                      0.0                 1.0                     0.0                    1.0                   0.0            0.0          0.0           1.0                        0.0                             0.0                          1.0              0.0              0.0              0.0              1.0              0.0              0.0            0.0                0.0                       0.0               1.0                      0.0                  0.0                      0.0                       1.0                      0.0                           0.0   78459       0.282478             -0.846476   1.461898       0.263104             0.827024             -1.511710               0.249244          -0.345443                  0.869079  0.894601            0.345286      -0.114838
2               1.0               0.0               1.0               0.0               0.0                        0.0                       0.0                         1.0                      0.0                 0.0                     0.0                    0.0                   1.0            0.0          1.0           0.0                        1.0                             0.0                          0.0              0.0              0.0              0.0              0.0              1.0              0.0            0.0                0.0                       0.0               1.0                      0.0                  0.0                      1.0                       0.0                      0.0                           0.0  110125       0.011375              0.636238   1.461898       0.552369            -1.209155             -0.690638               0.967960          -0.345443                 -1.204855  1.758510            0.345286       0.623570
3               1.0               0.0               1.0               0.0               0.0                        0.0                       0.0                         1.0                      0.0                 0.0                     0.0                    1.0                   0.0            1.0          0.0           0.0                        1.0                             0.0                          0.0              0.0              0.0              1.0              0.0              0.0              0.0            0.0                0.0                       0.0               1.0                      0.0                  0.0                      1.0                       0.0                      0.0                           0.0   46998       0.011375              0.121649   1.461898      -0.431132             0.827024             -0.074834              -0.931505          -0.345443                  0.709344 -0.314870           -0.375352      -0.043254
4               1.0               0.0               1.0               0.0               0.0                        0.0                       0.0                         0.0                      0.0                 1.0                     1.0                    0.0                   0.0            1.0          0.0           0.0                        1.0                             0.0                          0.0              0.0              0.0              0.0              0.0              1.0              0.0            0.0                0.0                       0.0               1.0                      0.0                  0.0                      1.0                       0.0                      0.0                           0.0   90938       0.011375              1.238046  -0.293564       0.610222             0.827024              0.438336              -0.187120          -0.345443                  0.939781  1.499337            1.786562       0.359162

In [75]:
!pip install scikit-learn xgboost catboost lightgbm hyperopt bayesian-optimization

Requirement already satisfied: scikit-learn in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (1.6.1)
Requirement already satisfied: xgboost in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (3.0.0)
Requirement already satisfied: catboost in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (1.2.8)
Requirement already satisfied: lightgbm in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (4.6.0)
Requirement already satisfied: hyperopt in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (0.2.7)
Requirement already satisfied: bayesian-optimization in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (2.0.3)
Requirement already satisfied: numpy>=1.19.5 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from scikit-learn) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from scikit-learn) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: graphviz in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from catboost) (0.20.3)
Requirement already satisfied: matplotlib in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from catboost) (3.10.1)
Requirement already satisfied: pandas>=0.24 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from catboost) (2.2.3)
Requirement already satisfied: plotly in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from catboost) (6.0.1)
Requirement already satisfied: six in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: networkx>=2.2 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from hyperopt) (3.4.2)
Requirement already satisfied: future in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from hyperopt) (1.0.0)
Requirement already satisfied: tqdm in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from hyperopt) (4.67.1)
Requirement already satisfied: cloudpickle in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from hyperopt) (3.1.1)
Requirement already satisfied: py4j in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from hyperopt) (0.10.9.9)
Requirement already satisfied: colorama<0.5.0,>=0.4.6 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from bayesian-optimization) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from pandas>=0.24->catboost) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from pandas>=0.24->catboost) (2025.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->catboost) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->catboost) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->catboost) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from matplotlib->catboost) (3.2.1)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\kusha\anaconda3\envs\myenv\lib\site-packages (from plotly->catboost) (1.29.0)

MODEL TRAINING

In [76]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.linear_model import LogisticRegression
from catboost import CatBoostClassifier
import lightgbm as lgb
from lightgbm import LGBMRegressor
from sklearn.metrics import make_scorer, mean_absolute_error
from sklearn.metrics import mean_squared_error as MSE
from hyperopt import hp, fmin, tpe
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from bayes_opt import BayesianOptimization
from sklearn.model_selection import KFold, cross_val_score
from lightgbm import LGBMClassifier

In [77]:
svc = SVC()
knc = KNeighborsClassifier() #algorithm=ball_tree, leaf_size=10, n_neighbors=18, p=1, weights=distance
mnb = MultinomialNB()
dtc = DecisionTreeClassifier()
lrc = LogisticRegression()
rfc = RandomForestClassifier()
abc = AdaBoostClassifier()
bc = BaggingClassifier()
etc = ExtraTreesClassifier()
gbdt = GradientBoostingClassifier()
xgb = XGBClassifier()
cat = CatBoostClassifier(verbose=0) 
lgb = lgb.LGBMClassifier()

Random Forest

In [78]:
clf = {
    'rfc':rfc
}

In [79]:
from sklearn.metrics import precision_score, accuracy_score, recall_score, confusion_matrix

def train_classifier(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    specificity = tn / (tn + fp)
    
    return accuracy, precision, recall, specificity

In [80]:
X_new_train = X_new_train.drop(columns=[col for col in X_new_train.columns if pd.isna(col)], axis=1)
X_new_test = X_new_test.drop(columns=[col for col in X_new_test.columns if pd.isna(col)], axis=1)

In [81]:
accuracy_scores = []
precision_scores = []
recall_scores = []
specificity_scores = []

for name,clf in clf.items():
    
    current_accuracy,current_precision, current_recall, current_specificity = train_classifier(clf, X_new_train,y_train,X_new_test,y_test)
    
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    print("Recall - ",current_recall)
    print("Specificity - ",current_specificity)
    print()
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)
    recall_scores.append(current_recall)
    specificity_scores.append(current_specificity)

For  rfc
Accuracy -  0.7007441887193633
Precision -  0.29850746268656714
Recall -  0.0019252984212552945
Specificity -  0.9980749539217694

KNeighbors

In [82]:
clf = {
    'KN' : knc
}

In [83]:
from sklearn.metrics import precision_score, accuracy_score, recall_score, confusion_matrix

def train_classifier(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    
   
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    specificity = tn / (tn + fp)
    
    return accuracy, precision, recall, specificity

In [84]:
X_new_train = X_new_train.drop(columns=[col for col in X_new_train.columns if pd.isna(col)], axis=1)
X_new_test = X_new_test.drop(columns=[col for col in X_new_test.columns if pd.isna(col)], axis=1)

In [85]:
accuracy_scores = []
precision_scores = []
recall_scores = []
specificity_scores = []

for name,clf in clf.items():
    
    current_accuracy,current_precision, current_recall, current_specificity = train_classifier(clf, X_new_train,y_train,X_new_test,y_test)
    
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    print("Recall - ",current_recall)
    print("Specificity - ",current_specificity)
    print()
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)
    recall_scores.append(current_recall)
    specificity_scores.append(current_specificity)

For  KN
Accuracy -  0.6375599804614545
Precision -  0.3019572953736655
Recall -  0.16336157104351173
Specificity -  0.8393200901085398

Bagging Algorithm

In [101]:
clf = {

    'bc': bc
}


from sklearn.metrics import precision_score, accuracy_score, recall_score, confusion_matrix

def train_classifier(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    specificity = tn / (tn + fp)
    
    return accuracy, precision, recall, specificity


X_new_train = X_new_train.drop(columns=[col for col in X_new_train.columns if pd.isna(col)], axis=1)
X_new_test = X_new_test.drop(columns=[col for col in X_new_test.columns if pd.isna(col)], axis=1)


accuracy_scores = []
precision_scores = []
recall_scores = []
specificity_scores = []

for name,clf in clf.items():
    
    current_accuracy,current_precision, current_recall, current_specificity = train_classifier(clf, X_new_train,y_train,X_new_test,y_test)
    
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    print("Recall - ",current_recall)
    print("Specificity - ",current_specificity)
    print()
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)
    recall_scores.append(current_recall)
    specificity_scores.append(current_specificity)

For  bc
Accuracy -  0.6691951843231906
Precision -  0.2830698033166217
Recall -  0.07065845206006931
Specificity -  0.9238582838419005

Bagging Along with Balancing Techniques

In [ ]:
from imblearn.over_sampling import SMOTE
from sklearn.metrics import precision_score, accuracy_score, recall_score, confusion_matrix, f1_score
import pandas as pd

# Apply SMOTE 
smote = SMOTE(random_state=42)
X_train_balanced, y_train_balanced = smote.fit_resample(X_new_train, y_train)

clf = {
    'bc': bc
}

def train_classifier(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    specificity = tn / (tn + fp)
    
    return accuracy, precision, recall, specificity, f1

X_new_train = X_new_train.drop(columns=[col for col in X_new_train.columns if pd.isna(col)], axis=1)
X_new_test = X_new_test.drop(columns=[col for col in X_new_test.columns if pd.isna(col)], axis=1)

accuracy_scores = []
precision_scores = []
recall_scores = []
specificity_scores = []
f1_scores = []

for name, clf in clf.items():
    current_accuracy, current_precision, current_recall, current_specificity, current_f1 = train_classifier(
        clf, X_train_balanced, y_train_balanced, X_new_test, y_test
    )
    
    print("For", name)
    print("Accuracy    -", current_accuracy)
    print("Precision   -", current_precision)
    print("Recall      -", current_recall)
    print("Specificity -", current_specificity)
    print("F1 Score    -", current_f1)
    print()
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)
    recall_scores.append(current_recall)
    specificity_scores.append(current_specificity)
    f1_scores.append(current_f1)

For bc
Accuracy    - 0.6677872597189898
Precision   - 0.29154829545454547
Recall      - 0.07903350019252985
Specificity - 0.9182879377431906
F1 Score    - 0.12435625568009694

XGBoost and CatBoost

In [86]:
clf = {

    'xgb':xgb,
    'cat':cat
}


from sklearn.metrics import precision_score, accuracy_score, recall_score, confusion_matrix

def train_classifier(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    specificity = tn / (tn + fp)
    
    return accuracy, precision, recall, specificity


X_new_train = X_new_train.drop(columns=[col for col in X_new_train.columns if pd.isna(col)], axis=1)
X_new_test = X_new_test.drop(columns=[col for col in X_new_test.columns if pd.isna(col)], axis=1)


accuracy_scores = []
precision_scores = []
recall_scores = []
specificity_scores = []

for name,clf in clf.items():
    
    current_accuracy,current_precision, current_recall, current_specificity = train_classifier(clf, X_new_train,y_train,X_new_test,y_test)
    
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    print("Recall - ",current_recall)
    print("Specificity - ",current_specificity)
    print()
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)
    recall_scores.append(current_recall)
    specificity_scores.append(current_specificity)

For  xgb
Accuracy -  0.6939631640950493
Precision -  0.2767402376910017
Recall -  0.01569118213323065
Specificity -  0.9825517100143355

For  cat
Accuracy -  0.7006005229434245
Precision -  0.32222222222222224
Recall -  0.002791682710820177
Specificity -  0.9975015359410199

XGBoost and CatBoost using Sampling Techniques

In [87]:
from imblearn.over_sampling import SMOTE
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import precision_score, accuracy_score, recall_score, confusion_matrix, f1_score

def train_classifier(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    specificity = tn / (tn + fp)
    return accuracy, precision, recall, specificity, f1

# Apply SMOTE to your training data only
sm = SMOTE(random_state=42, k_neighbors=1)
X_train_resampled, Y_train_resampled = sm.fit_resample(X_new_train, y_train)

# Define classifiers
xgb = XGBClassifier(use_label_encoder=False, eval_metric='logloss')
cat = CatBoostClassifier(verbose=0)
clf_dict = {'xgb': xgb, 'cat': cat}

# Train and evaluate with F1 score
for name, clf in clf_dict.items():
    acc, prec, rec, spec, f1 = train_classifier(clf, X_train_resampled, Y_train_resampled, X_new_test, y_test)
    print(f"For {name}")
    print(f"Accuracy - {acc}")
    print(f"Precision - {prec}")
    print(f"Recall - {rec}")
    print(f"Specificity - {spec}")
    print(f"F1 Score - {f1}\n")

For xgb
Accuracy - 0.6954572881648133
Precision - 0.27789473684210525
Recall - 0.012706969580284944
Specificity - 0.9859512594716363
F1 Score - 0.024302678818006077

For cat
Accuracy - 0.700025859839669
Precision - 0.32666666666666666
Recall - 0.0047169811320754715
Specificity - 0.995863198853164
F1 Score - 0.009299677358132473

Xgboost using Hyperparameters and ADASYN

In [ ]:
from imblearn.over_sampling import ADASYN
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import precision_score, accuracy_score, recall_score, confusion_matrix, f1_score

# classifiers
xgboost_optimal_high = XGBClassifier(
    base_score=0.5, booster='gbtree', colsample_bylevel=1,
    colsample_bynode=1, colsample_bytree=1, gamma=0,
    learning_rate=0.01, max_delta_step=0, max_depth=10,
    min_child_weight=1, n_estimators=1000, n_jobs=-1,
    nthread=None, objective='binary:logistic', random_state=0,
    reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
    silent=None, subsample=1, verbosity=1
)
cat = CatBoostClassifier(verbose=0)
clf_dict = {'xgb_optimal_high': xgboost_optimal_high, 'cat': cat}


def train_classifier(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    specificity = tn / (tn + fp)
    return accuracy, precision, recall, specificity, f1

# Apply ADASYN 
ada = ADASYN(random_state=42)
X_train_resampled, Y_train_resampled = ada.fit_resample(X_new_train, y_train)


for name, clf in clf_dict.items():
    acc, prec, rec, spec, f1 = train_classifier(clf, X_train_resampled, Y_train_resampled, X_new_test, y_test)
    print(f"For {name}")
    print(f"Accuracy - {acc}")
    print(f"Precision - {prec}")
    print(f"Recall - {rec}")
    print(f"Specificity - {spec}")
    print(f"F1 Score - {f1}\n")

For xgb_optimal_high
Accuracy - 0.7002269919259834
Precision - 0.3008849557522124
Recall - 0.0032730073161340006
Specificity - 0.9967642842514848
F1 Score - 0.006475573754880487

For cat
Accuracy - 0.6998821940637301
Precision - 0.31125827814569534
Recall - 0.004524451289949942
Specificity - 0.9957403235715748
F1 Score - 0.008919252300977322

Hyperparameters and ADASYN using Default HYPERPARAMETERS

In [ ]:
from sklearn.model_selection import train_test_split
from imblearn.over_sampling import ADASYN
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import precision_score, accuracy_score, recall_score, confusion_matrix, f1_score


# Define classifiers
xgb = XGBClassifier()
cat = CatBoostClassifier(verbose=0)
clf_dict = {'xgb': xgb, 'cat': cat}

def train_classifier(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    specificity = tn / (tn + fp)
    return accuracy, precision, recall, specificity, f1

# Apply ADASYN to training data
ada = ADASYN(random_state=42)
X_train_resampled, Y_train_resampled = ada.fit_resample(X_new_train, y_train)

# Train and evaluate
results = {}
for name, clf in clf_dict.items():
    acc, prec, rec, spec, f1 = train_classifier(clf, X_train_resampled, Y_train_resampled, X_new_test, y_test)
    results[name] = {'Accuracy': acc, 'Precision': prec, 'Recall': rec, 'Specificity': spec, 'F1 Score': f1}

print(results)

{'xgb': {'Accuracy': 0.6956584202511278, 'Precision': 0.2875, 'Recall': 0.013284559106661533, 'Specificity': 0.9859922178988327, 'F1 Score': 0.025395656974604344}, 'cat': {'Accuracy': 0.6998821940637301, 'Precision': 0.31125827814569534, 'Recall': 0.004524451289949942, 'Specificity': 0.9957403235715748, 'F1 Score': 0.008919252300977322}}

In [91]:
print(X_train_resampled.shape)
print(Y_train_resampled.shape)

(117746, 48)
(117746,)

Resampling Using Class Weights Approach using CatBoost

In [92]:
# Paying attention to minority class

from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

# Calculate class weights
neg = (y_train == 0).sum()
pos = (y_train == 1).sum()
class_weights = [1, neg / pos]


cat = CatBoostClassifier(class_weights=class_weights, random_state=42, verbose=0)
cat.fit(X_new_train, y_train)

y_pred = cat.predict(X_new_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
specificity = tn / (tn + fp)

print("CatBoost with class weights:")
print(f"Accuracy     : {accuracy:.4f}")
print(f"Precision    : {precision:.4f}")
print(f"Recall       : {recall:.4f}")
print(f"Specificity  : {specificity:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred, zero_division=0))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

CatBoost with class weights:
Accuracy     : 0.5335
Precision    : 0.2968
Recall       : 0.4111
Specificity  : 0.5856

Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.59      0.64     24415
           1       0.30      0.41      0.34     10388

    accuracy                           0.53     34803
   macro avg       0.50      0.50      0.49     34803
weighted avg       0.58      0.53      0.55     34803

Confusion Matrix:
 [[14297 10118]
 [ 6117  4271]]

SMOTE + CatBoost

In [93]:
# Using SMOTE for balancing the data 

from imblearn.over_sampling import SMOTE
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

# Apply SMOTE
sm = SMOTE(random_state=42)
X_res, y_res = sm.fit_resample(X_new_train, y_train)

neg = (y_train == 0).sum()
pos = (y_train == 1).sum()
class_weights = [1, neg / pos]

cat = CatBoostClassifier(class_weights=class_weights, random_state=42, verbose=0)
cat.fit(X_res, y_res)

y_pred = cat.predict(X_new_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
specificity = tn / (tn + fp)

print("CatBoost with SMOTE oversampling and class weights:")
print(f"Accuracy     : {accuracy:.4f}")
print(f"Precision    : {precision:.4f}")
print(f"Recall       : {recall:.4f}")
print(f"Specificity  : {specificity:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred, zero_division=0))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

CatBoost with SMOTE oversampling and class weights:
Accuracy     : 0.5122
Precision    : 0.2927
Recall       : 0.4477
Specificity  : 0.5396

Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.54      0.61     24415
           1       0.29      0.45      0.35     10388

    accuracy                           0.51     34803
   macro avg       0.49      0.49      0.48     34803
weighted avg       0.58      0.51      0.53     34803

Confusion Matrix:
 [[13175 11240]
 [ 5737  4651]]

Undersampling The Majority Class

In [94]:
# Undersample the majority class

from imblearn.under_sampling import RandomUnderSampler
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

#  Apply RandomUnderSampler to train
rus = RandomUnderSampler(random_state=42)
X_res, y_res = rus.fit_resample(X_new_train, y_train)

neg = (y_res == 0).sum()
pos = (y_res == 1).sum()
class_weights = [1, neg / pos]

cat = CatBoostClassifier(class_weights=class_weights, random_state=42, verbose=0)
cat.fit(X_res, y_res)

y_pred = cat.predict(X_new_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, zero_division=0)
recall = recall_score(y_test, y_pred, zero_division=0)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
specificity = tn / (tn + fp)

print("CatBoost with RandomUnderSampler (undersampling majority class):")
print(f"Accuracy     : {accuracy:.4f}")
print(f"Precision    : {precision:.4f}")
print(f"Recall       : {recall:.4f}")
print(f"Specificity  : {specificity:.4f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred, zero_division=0))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

CatBoost with RandomUnderSampler (undersampling majority class):
Accuracy     : 0.5021
Precision    : 0.2964
Recall       : 0.4863
Specificity  : 0.5089

Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.51      0.59     24415
           1       0.30      0.49      0.37     10388

    accuracy                           0.50     34803
   macro avg       0.50      0.50      0.48     34803
weighted avg       0.58      0.50      0.52     34803

Confusion Matrix:
 [[12424 11991]
 [ 5336  5052]]

AdaBoost and Logistic Regression

In [95]:
clf = {

    'abc':abc,
    'lrc':lrc
}


from sklearn.metrics import precision_score, accuracy_score, recall_score, confusion_matrix

def train_classifier(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)

    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    specificity = tn / (tn + fp)
    
    return accuracy, precision, recall, specificity


X_new_train = X_new_train.drop(columns=[col for col in X_new_train.columns if pd.isna(col)], axis=1)
X_new_test = X_new_test.drop(columns=[col for col in X_new_test.columns if pd.isna(col)], axis=1)


accuracy_scores = []
precision_scores = []
recall_scores = []
specificity_scores = []

for name,clf in clf.items():
    
    current_accuracy,current_precision, current_recall, current_specificity = train_classifier(clf, X_new_train,y_train,X_new_test,y_test)
    
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    print("Recall - ",current_recall)
    print("Specificity - ",current_specificity)
    print()
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)
    recall_scores.append(current_recall)
    specificity_scores.append(current_specificity)

For  abc
Accuracy -  0.701519983909433
Precision -  0.0
Recall -  0.0
Specificity -  1.0

For  lrc
Accuracy -  0.701519983909433
Precision -  0.0
Recall -  0.0
Specificity -  1.0

LightGBM

In [96]:
clf = {

    'lgb':lgb
}


from sklearn.metrics import precision_score, accuracy_score, recall_score, confusion_matrix

def train_classifier(clf, X_train, y_train, X_test, y_test):
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    
    
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    specificity = tn / (tn + fp)
    
    return accuracy, precision, recall, specificity


X_new_train = X_new_train.drop(columns=[col for col in X_new_train.columns if pd.isna(col)], axis=1)
X_new_test = X_new_test.drop(columns=[col for col in X_new_test.columns if pd.isna(col)], axis=1)


accuracy_scores = []
precision_scores = []
recall_scores = []
specificity_scores = []

for name,clf in clf.items():
    
    current_accuracy,current_precision, current_recall, current_specificity = train_classifier(clf, X_new_train,y_train,X_new_test,y_test)
    
    print("For ",name)
    print("Accuracy - ",current_accuracy)
    print("Precision - ",current_precision)
    print("Recall - ",current_recall)
    print("Specificity - ",current_specificity)
    print()
    
    accuracy_scores.append(current_accuracy)
    precision_scores.append(current_precision)
    recall_scores.append(current_recall)
    specificity_scores.append(current_specificity)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 24414, number of negative: 56792
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002485 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1615
[LightGBM] [Info] Number of data points in the train set: 81206, number of used features: 47
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.300643 -> initscore=-0.844239
[LightGBM] [Info] Start training from score -0.844239
For  lgb
Accuracy -  0.7013188518231187
Precision -  0.3157894736842105
Recall -  0.0005775895263765884
Specificity -  0.9994675404464468

 Bayesian Optimization for Hyperparameter Tuning

In [ ]:
from bayes_opt import BayesianOptimization
from sklearn.model_selection import cross_val_score, StratifiedKFold
from lightgbm import LGBMClassifier
import numpy as np
X_subset = X_new_train[:40000]
y_subset = y_train[:40000]

def lgbm_clf_bo(max_depth, num_leaves, learning_rate, min_child_weight, subsample, colsample_bytree):
    max_depth = int(round(max_depth))
    num_leaves = int(round((2 ** max_depth) * num_leaves))

    params = {
        'objective': 'binary',
        'random_state': 42,
        'boosting_type': 'gbdt',
        'metric': 'recall',
        'max_depth': max_depth,
        'num_leaves': num_leaves,
        'learning_rate': learning_rate,
        'min_child_weight': min_child_weight,
        'subsample': subsample,
        'colsample_bytree': colsample_bytree,
        'n_jobs': -1,
        'verbosity': -1
    }
    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    score = cross_val_score(
        LGBMClassifier(**params), X_subset, y_subset, 
        scoring='recall', cv=cv, n_jobs=-1
    ).mean()

    return score
params_bounds = {
    'max_depth': (3, 10),
    'num_leaves': (0.1, 1), 
    'learning_rate': (0.01, 0.3),
    'min_child_weight': (1e-6, 1e-1),
    'subsample': (0.6, 1.0),
    'colsample_bytree': (0.6, 1.0)
}

lgbm_bo = BayesianOptimization(f=lgbm_clf_bo, pbounds=params_bounds, random_state=42, verbose=2)
lgbm_bo.maximize(init_points=3, n_iter=20)

|   iter    |  target   | colsam... | learni... | max_depth | min_ch... | num_le... | subsample |
-------------------------------------------------------------------------------------------------
| 1         | 0.05677   | 0.7498    | 0.2857    | 8.124     | 0.05987   | 0.2404    | 0.6624    |
| 2         | 0.01044   | 0.6232    | 0.2612    | 7.208     | 0.07081   | 0.1185    | 0.988     |
| 3         | 8.288e-05 | 0.933     | 0.07158   | 4.273     | 0.01834   | 0.3738    | 0.8099    |
| 4         | 0.0479    | 0.9014    | 0.2587    | 7.131     | 0.03663   | 0.4969    | 0.9145    |
| 5         | 0.04417   | 0.6497    | 0.2167    | 8.185     | 0.01564   | 0.6704    | 0.954     |
| 6         | 0.006795  | 0.6841    | 0.2978    | 4.497     | 0.07011   | 0.5461    | 0.7151    |
| 7         | 0.03795   | 0.9158    | 0.1653    | 9.263     | 0.04574   | 0.4802    | 0.8615    |
| 8         | 0.06588   | 0.7426    | 0.2838    | 8.155     | 0.05017   | 0.2783    | 0.6544    |
| 9         | 0.001243  | 0.8913    | 0.1367    | 5.953     | 0.003043  | 0.1681    | 0.8665    |
| 10        | 0.02668   | 0.8016    | 0.1679    | 8.29      | 0.07371   | 0.4252    | 0.6618    |
| 11        | 0.05469   | 0.6058    | 0.2633    | 8.184     | 0.06577   | 0.3082    | 0.6534    |
| 12        | 0.03862   | 0.7381    | 0.2508    | 8.277     | 0.03429   | 0.1827    | 0.69      |
| 13        | 0.0009944 | 0.9502    | 0.107     | 5.352     | 0.09408   | 0.5929    | 0.6897    |
| 14        | 0.07956   | 0.7567    | 0.295     | 8.106     | 0.01323   | 0.4248    | 0.7193    |
| 15        | 0.06282   | 0.659     | 0.2577    | 8.013     | 0.04087   | 0.4407    | 0.6206    |
| 16        | 0.06273   | 0.7132    | 0.2643    | 8.105     | 0.01499   | 0.3722    | 0.6943    |
| 17        | 0.07036   | 0.8719    | 0.267     | 7.995     | 0.0613    | 0.554     | 0.7002    |
| 18        | 0.08163   | 0.7906    | 0.2982    | 8.044     | 0.04214   | 0.4561    | 0.9318    |
| 19        | 0.07947   | 0.9813    | 0.2902    | 7.914     | 0.02549   | 0.3487    | 0.895     |
| 20        | 0.02403   | 0.6888    | 0.1915    | 7.142     | 0.001278  | 0.8427    | 0.7079    |
| 21        | 0.08353   | 0.9408    | 0.2904    | 7.84      | 0.05786   | 0.5954    | 0.9751    |
| 22        | 0.07201   | 0.919     | 0.2679    | 7.813     | 0.02237   | 0.6397    | 0.9463    |
| 23        | 0.07442   | 0.974     | 0.2804    | 7.671     | 0.06523   | 0.4534    | 0.9435    |
=================================================================================================

Implementing The above mentiioned hypertuned results in Model training using lightgbm

In [ ]:
from lightgbm import LGBMClassifier

best_params = lgbm_bo.max['params']
best_params['max_depth'] = int(round(best_params['max_depth']))
best_params['num_leaves'] = int(round((2 ** best_params['max_depth']) * best_params['num_leaves']))

optimized_lgbm = LGBMClassifier(
    objective='binary',
    random_state=42,
    boosting_type='gbdt',
    metric='recall',
    max_depth=best_params['max_depth'],
    num_leaves=best_params['num_leaves'],
    learning_rate=best_params['learning_rate'],
    min_child_weight=best_params['min_child_weight'],
    subsample=best_params['subsample'],
    colsample_bytree=best_params['colsample_bytree'],
    n_jobs=-1,
    verbosity=-1
)

optimized_lgbm.fit(X_new_train, y_train)


y_pred = optimized_lgbm.predict(X_new_test)


from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
specificity = tn / (tn + fp)

print("Optimized Model Performance:")
print(f"Accuracy     - {accuracy}")
print(f"Precision    - {precision}")
print(f"Recall       - {recall}")
print(f"Specificity  - {specificity}")
print(f"F1 Score     - {f1}")

Best Hyperparameters from Bayesian Optimization:
{'colsample_bytree': 0.9408151953485889, 'learning_rate': 0.2904314526226584, 'max_depth': 8, 'min_child_weight': 0.05785789298926823, 'num_leaves': 152, 'subsample': 0.9750737408446817}
Optimized Model Performance:
Accuracy     - 0.6820963710024998
Precision    - 0.2796610169491525
Recall       - 0.04129765113592607
Specificity  - 0.9547409379479828
F1 Score     - 0.07196779063915451

Implementing The above mentiioned hypertuned results in Model training using XGBoost

In [ ]:
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, f1_score

best_params = lgbm_bo.max['params']
best_params['max_depth'] = int(round(best_params['max_depth']))
best_params['num_leaves'] = int(round((2 ** best_params['max_depth']) * best_params['num_leaves']))

best_params['n_estimators'] = 100  

optimized_xgb = XGBClassifier(
    objective='binary:logistic',
    random_state=42,
    max_depth=best_params['max_depth'],
    n_estimators=best_params['n_estimators'],
    learning_rate=best_params['learning_rate'],
    min_child_weight=best_params['min_child_weight'],
    subsample=best_params['subsample'],
    colsample_bytree=best_params['colsample_bytree'],
    verbosity=0  
)


optimized_xgb.fit(X_new_train, y_train)

y_pred = optimized_xgb.predict(X_new_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
specificity = tn / (tn + fp)

print("\nOptimized XGBoost Model Performance:")
print(f"Accuracy     - {accuracy}")
print(f"Precision    - {precision}")
print(f"Recall       - {recall}")
print(f"Specificity  - {specificity}")
print(f"F1 Score     - {f1}")

Best Hyperparameters from Bayesian Optimization:
{'colsample_bytree': 0.9408151953485889, 'learning_rate': 0.2904314526226584, 'max_depth': 8, 'min_child_weight': 0.05785789298926823, 'num_leaves': 152, 'subsample': 0.9750737408446817, 'n_estimators': 100}

Optimized XGBoost Model Performance:
Accuracy     - 0.6820676378473121
Precision    - 0.29982259018332347
Recall       - 0.048806314978821715
Specificity  - 0.9515052221994675
F1 Score     - 0.08394734663465518

In [112]:
params_lgbm = lgbm_bo.max['params']
params_lgbm['max_depth'] = round(params_lgbm['max_depth'])
params_lgbm['num_leaves'] = round((2**round(params_lgbm['max_depth']))*params_lgbm['num_leaves'])
params_lgbm

{'colsample_bytree': 0.9408151953485889,
 'learning_rate': 0.2904314526226584,
 'max_depth': 8,
 'min_child_weight': 0.05785789298926823,
 'num_leaves': 152,
 'subsample': 0.9750737408446817}

LightGBM(hypertuned)+KNN+CatBoost  Ensemble Modeling

In [ ]:
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

lgbm_model = LGBMClassifier(
    objective='binary',
    random_state=42,
    boosting_type='gbdt',
    metric='recall',
    max_depth=params_lgbm['max_depth'],
    num_leaves=params_lgbm['num_leaves'],
    learning_rate=params_lgbm['learning_rate'],
    min_child_weight=params_lgbm['min_child_weight'],
    subsample=params_lgbm['subsample'],
    colsample_bytree=params_lgbm['colsample_bytree'],
    n_jobs=-1,
    verbosity=-1
)
knn_model = KNeighborsClassifier(n_neighbors=7, weights='distance', metric='minkowski')
catboost_model = CatBoostClassifier(iterations=300, learning_rate=0.05, depth=6, l2_leaf_reg=3, verbose=0)

ensemble_model = VotingClassifier(
    estimators=[('lgbm', lgbm_model), ('knn', knn_model), ('catboost', catboost_model)],
    voting='soft',  
    weights=[2, 1, 1], 
    verbose=0
)

ensemble_model.fit(X_new_train, y_train)

y_pred = ensemble_model.predict(X_new_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
specificity = tn / (tn + fp)

print("\nEnsemble Model Performance:")
print(f"Accuracy     - {accuracy}")
print(f"Precision    - {precision}")
print(f"Recall       - {recall}")
print(f"Specificity  - {specificity}")
print(f"F1 Score     - {f1}")

Ensemble Model Performance:
Accuracy     - 0.6983593368387783
Precision    - 0.2868217054263566
Recall       - 0.00712360415864459
Specificity  - 0.9924636493958632
F1 Score     - 0.013901934999060681

Final Model Training (Ensemble Coding using KNN,XGBOOST,CatBoost,LightGBM)

In [99]:
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier


knn = KNeighborsClassifier()
cat = CatBoostClassifier(verbose=0)
lgb = LGBMClassifier()


ensemble = VotingClassifier(estimators=[('knn', knn),  ('cat', cat), ('lgb', lgb)], voting='soft',verbose=0)
current_accuracy,current_precision, current_recall, current_specificity = train_classifier(ensemble, X_new_train, y_train, X_new_test, y_test)

print("For ensemble")
print("Accuracy - ",current_accuracy)
print("Precision - ",current_precision)
print("Recall - ",current_recall)
print("Specificity - ",current_specificity)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 24414, number of negative: 56792
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002490 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1615
[LightGBM] [Info] Number of data points in the train set: 81206, number of used features: 47
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.300643 -> initscore=-0.844239
[LightGBM] [Info] Start training from score -0.844239
For ensemble
Accuracy -  0.7001120593052323
Precision -  0.3157894736842105
Recall -  0.004043126684636119
Specificity -  0.996272783125128

In [100]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor()
from sklearn.feature_selection import RFE

clf = RandomForestRegressor()


clf.fit(X_new_train,y_train)

feature_scores = pd.Series(clf.feature_importances_, index=X_new_train.columns).sort_values(ascending=False)
feature_scores

index                             0.126531
Annual Income                     0.104394
borrower_credit_score             0.100404
unpaid_principal_bal              0.088713
loan_to_value                     0.075698
Age                               0.068856
debt_to_income_ratio              0.065207
interest_rate                     0.064562
co-borrower_credit_score          0.060643
Loan_term                         0.037994
NumberOfDependents                0.034864
EducationLevel_Bachelor's         0.010408
EducationLevel_High School        0.010074
EducationLevel_PhD                0.009484
MaritalStatus_Married             0.009018
MaritalStatus_Single              0.008868
EducationLevel_Master's           0.008827
loan_purpose_A23                  0.008512
loan_purpose_B12                  0.008331
Gender_Female                     0.008291
MaritalStatus_Divorced            0.008209
loan_purpose_C86                  0.007704
Gender_Male                       0.007663
EmploymentStatus_Self-Employed    0.007217
EmploymentStatus_Employed         0.006496
insurance_percent                 0.006428
EducationLevel_Doctorate          0.005922
Gender_Other                      0.005306
age_group_35-44                   0.005073
EmploymentStatus_Unemployed       0.004470
age_group_25-34                   0.004440
age_group_45-54                   0.004118
number_of_borrowers               0.003950
age_group_18-24                   0.003048
age_group_55-64                   0.002445
loan_amount_group_medium          0.001806
loan_amount_group_large           0.001777
age_group_nan                     0.001405
age_group_65-79                   0.000694
insurance_type_1                  0.000398
insurance_type_0                  0.000374
loan_amount_group_very large      0.000370
loan_amount_group_small           0.000370
income_group_low-middle           0.000295
income_group_low                  0.000240
income_group_middle               0.000071
income_group_high-middle          0.000016
income_group_high                 0.000013
dtype: float64